# Generated by Django 4.1.5 on 2023-01-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category title')),
                ('description', models.TextField(max_length=150, verbose_name='Category description')),
                ('is_active', models.BooleanField(verbose_name='Category is active')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Game Name')),
                ('description', models.CharField(max_length=140, verbose_name='Game Description')),
                ('is_active', models.BooleanField(verbose_name='Game is active?')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publish date')),
                ('release_date_at', models.DateTimeField(auto_now_add=True, verbose_name='Release date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Game Prise')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('game_image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.category', verbose_name='Game Category')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
