# Generated by Django 4.1.5 on 2023-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_game_release_date_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='games_amount',
            field=models.IntegerField(default=0, verbose_name='amount'),
        ),
    ]
