# Generated by Django 4.1.5 on 2023-01-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_shopinfomixin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
