# Generated by Django 4.1.5 on 2023-01-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_rename_name_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
    ]
