# Generated by Django 4.1.5 on 2023-01-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_rename_title_game_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
