# Generated by Django 4.1.5 on 2023-02-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_game_games_game_title_b7a574_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TimeField(max_length=150, verbose_name='Comment text')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Comment publication date')),
                ('rating', models.IntegerField(verbose_name='Comment rating')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
