# Generated by Django 4.1.5 on 2023-02-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_alter_comment_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(max_length=5, verbose_name='Comment rating'),
        ),
    ]
