# Generated by Django 4.1.5 on 2023-01-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_release_date_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='publish date'),
        ),
    ]
