# Generated by Django 4.1.5 on 2023-01-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Game Description'),
        ),
    ]
