# Generated by Django 4.1.5 on 2023-01-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date_at',
            field=models.DateField(migrations.DeleteModel(
                name="release_date_at",
            )
            )
        ),
    ]
