# Generated by Django 4.1.5 on 2023-01-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
