# Generated by Django 4.1.5 on 2023-01-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_rename_title_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
